app:
  chains:
    rpc: #Chain RPC
    chainId: #Chain ID
    controllerAddress: #Controller address
    tokenAddress: #Token address
    nftAddress: #NFT address
    privateKey: #User private key
  cron:
    jobs:
      - name: FilterLogsJob
        spec: "@every 3s"
